In [1]:
import os
os.chdir('C://Users//17731//PycharmProjects//transformer_test_github//transformer_test')

In [4]:
from utils import generate_padding_mask, generate_future_mask, combine_padding_mask
import torch

batch_size = 2
seq_length = 5
source = torch.tensor([
    [1, 2, 0, 0, 0],
    [4, 5, 6, 0, 0]
])

target = torch.tensor([
    [1, 2, 4, 0, 0],
    [4, 5, 6, 9, 0]
])





In [5]:
padding_mask = (source == 0).unsqueeze(1).unsqueeze(2)
padding_mask.shape
padding_mask = padding_mask | padding_mask.transpose(-2, -1)
padding_mask.shape

padding_mask2 = (target == 0).unsqueeze(1).unsqueeze(2)
padding_mask2 = padding_mask2 | padding_mask2.transpose(-2, -1)

a = padding_mask2[:, :, 0, :].unsqueeze(3)
a.shape
b = padding_mask[:, :, :, 0].unsqueeze(2)
c = a | b
c


tensor([[[[False, False,  True,  True,  True],
          [False, False,  True,  True,  True],
          [False, False,  True,  True,  True],
          [ True,  True,  True,  True,  True],
          [ True,  True,  True,  True,  True]]],


        [[[False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [ True,  True,  True,  True,  True]]]])

In [6]:
size = 5
future_mask = torch.triu(torch.ones(size, size, dtype=torch.bool), diagonal=1)
future_mask

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [7]:
from models import MachineTranslation
import torch.nn as nn
from models.positional_encoding import PositionalEncoding
d_model = 512
n_head = 8
n_encoder_layers = 6
n_decoder_layers = 6
d_feedforward = 2048
dropout = 0.1
lr = 0.01
batch_size = 32
pad_token = 0
source_vocab_dim = 7
target_vocab_dim = 7

source = torch.tensor([
    [1, 2, 0, 0, 0],
    [4, 5, 6, 0, 0]
])

target = torch.tensor([
    [1, 2, 4, 0, 0],
    [4, 5, 6, 3, 0]
])

# model = MachineTranslation(source_vocab_dim, target_vocab_dim, d_model, n_head, n_encoder_layers, n_decoder_layers, d_feedforward, pad_token,
#                  dropout)
# output = model(source, target)
source_embedding = nn.Embedding(source_vocab_dim, d_model)
em = source_embedding(source)
pe = PositionalEncoding(d_model)
output = pe(em)
output

tensor([[[-1.0695,  2.6276, -1.7287,  ...,  1.1041, -0.2481,  1.7539],
         [ 1.5410,  0.7383, -0.5964,  ...,  0.4142,  1.0353,  2.6996],
         [ 0.1716,  0.5476,  0.8261,  ...,  2.2084, -0.1552,  2.0457],
         [ 0.1716,  0.5476,  0.8261,  ...,  2.2084, -0.1552,  2.0457],
         [ 0.1716,  0.5476,  0.8261,  ...,  2.2084, -0.1552,  2.0457]],

        [[ 1.4200,  1.9027,  1.3466,  ..., -0.5245,  0.6404,  1.2608],
         [-0.2201,  0.2803, -0.4030,  ...,  1.2860, -0.0074,  1.1265],
         [ 1.2590,  1.5027,  1.5761,  ...,  0.6505,  1.3239,  0.6336],
         [ 1.0130,  0.0879,  1.6480,  ...,  2.2084, -0.1551,  2.0457],
         [ 1.0130,  0.0879,  1.6480,  ...,  2.2084, -0.1551,  2.0457]]],
       grad_fn=<AddBackward0>)