In [2]:
import os
os.chdir('C:\\Users\\17731\\PycharmProjects\\Transformer_test')

In [4]:
from utils import generate_padding_mask, generate_future_mask, combine_padding_mask
import torch

batch_size = 2
seq_length = 5
source = torch.tensor([
    [1, 2, 0, 0, 0],
    [4, 5, 6, 0, 0]
])

target = torch.tensor([
    [1, 2, 4, 0, 0],
    [4, 5, 6, 9, 0]
])





In [5]:
padding_mask = (source == 0).unsqueeze(1).unsqueeze(2)
padding_mask.shape
padding_mask = padding_mask | padding_mask.transpose(-2, -1)
padding_mask.shape

padding_mask2 = (target == 0).unsqueeze(1).unsqueeze(2)
padding_mask2 = padding_mask2 | padding_mask2.transpose(-2, -1)

a = padding_mask2[:, :, 0, :].unsqueeze(3)
a.shape
b = padding_mask[:, :, :, 0].unsqueeze(2)
c = a | b
c


tensor([[[[False, False,  True,  True,  True],
          [False, False,  True,  True,  True],
          [False, False,  True,  True,  True],
          [ True,  True,  True,  True,  True],
          [ True,  True,  True,  True,  True]]],


        [[[False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [False, False, False,  True,  True],
          [ True,  True,  True,  True,  True]]]])

In [6]:
size = 5
future_mask = torch.triu(torch.ones(size, size, dtype=torch.bool), diagonal=1)
future_mask

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [8]:
from models import MachineTranslation

d_model = 512
n_head = 8
n_encoder_layers = 6
n_decoder_layers = 6
d_feedforward = 2048
dropout = 0.1
lr = 0.01
batch_size = 32
pad_token = 0
source_vocab_dim = 7
target_vocab_dim = 7

source = torch.tensor([
    [1, 2, 0, 0, 0],
    [4, 5, 6, 0, 0]
])

target = torch.tensor([
    [1, 2, 4, 0, 0],
    [4, 5, 6, 3, 0]
])

model = MachineTranslation(source_vocab_dim, target_vocab_dim, d_model, n_head, n_encoder_layers, n_decoder_layers, d_feedforward, pad_token,
                 dropout)
output = model(source, target)


output

tensor([[[ 1.2176, -0.4382,  0.2044,  0.5766, -0.7130, -0.2128,  0.5365],
         [ 1.1081,  0.0927,  0.8679,  0.4075,  0.2052, -0.1806,  0.3666],
         [ 0.8568,  0.3828, -0.0980, -0.2425,  1.0655, -0.0875,  1.2476],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan]],

        [[-0.1438,  0.6958, -0.8632, -0.0981,  0.6014, -0.4976,  0.5719],
         [ 0.7860, -0.1021, -1.0673, -0.2604,  0.1355,  0.1291,  0.0415],
         [-0.3310,  0.0623, -0.1925,  0.5558, -0.1435, -0.1902, -0.3627],
         [ 0.0159,  0.2489, -1.1790, -0.7719,  0.5051, -0.9917, -0.1984],
         [    nan,     nan,     nan,     nan,     nan,     nan,     nan]]],
       grad_fn=<ViewBackward0>)